### ISSUE TITLE
Doesn't work for cnn.com

### ISSUE THREAD

**Issue by richlee91** [jaredsohn/mutetab#3]
I set cnn.com to be on the black list then I goto cnn.com and hit a story and it starts playing unmuted.

**Comment by jaredsohn** [comment]
It just worked for me. Some ideas for troubleshooting:

* If cnn was already loaded before you added it to the blacklist, then you need to manually mute it (or open a new tab on the site for it to be muted on load.)
* Check options to see if it saved the changes you made to the blacklist. (You need to click the save button after making changes.)
* Check what you added to the blacklist. Did you manually type in 'cnn.com' in options or is it www.cnn.com? If the latter, does that match the domain of the story that wasn't muted?
* Make sure the tab wasn't opened in an incognito tab, unless the extension is set up to work with incognito tabs.

If needed, include a screenshot of the blacklist in options and a story url. Provide instructions so I can try it myself (i.e. set those options and then open that url or go to cnn.com and click on the first story.)

**Comment by richlee91** [comment]
jared, thank you for your reply.  I used cnn.com and it indicated that it's on the black list see screenshot.  The tab is playing audio and on the right it's on the black list.
![image](https://cloud.githubusercontent.com/assets/24630720/24816301/27310994-1ba6-11e7-8449-77dce2a4fb9b.png)

**Comment by richlee91** [comment]
Sometimes it works sometimes it doesn't.  CNN seems to delay the playing of some videos.  So the page may be loaded and then 15 seconds go by and it starts playing.

**Comment by richlee91** [comment]
I have also tried disabling ublock also here are my settings.
![image](https://cloud.githubusercontent.com/assets/24630720/24816523/171b1a62-1ba7-11e7-97b7-6c549d75700f.png)

(Let me know if I'm stupid)  :)

**Comment by jaredsohn** [comment]
Everything looks like it should work.

I am assuming that cnn.com was in the blacklist and you had started the extension before you visited the site and that the options dialog in the screenshot was like this (and saved) after you visited the site. I also assume the default muting behavior is unmuted (it was cut off in the screenshot but since your other tabs aren't muted it seems likely.) Further, I assume you aren't running any other extension that mutes/unmutes tabs.

FYI, It shouldn't matter when the video starts; the tab should show the muted icon right away whenever you load a cnn.com webpage. Also, ublock shouldn't affect it since the javascript that does the muting is extension code which ublock cannot affect.

Some more questions:

Does manual muting via the extension work? 

Does the blacklist work for other sites? (or is it just an issue with cnn.com?)

Can you look at why the tab thinks it is unmuted? (In case it was muted and then unmuted again). To do so, go to the cnn tab, look at the extension UI, and highlight the speaker next to the cnn information; it will tell you why it is not unmuted underneath the tooltip 'Mute' if it was unmuted at some point.

What version of Chrome are you running? It works for me on Version 57.0.2987.133 (64-bit).

**Comment by jaredsohn** [comment]
@richlee91 I just made a fix (v3.0.6) which should be available in a few hours for another user's problem; maybe it fixed things for you, too?

**Comment by richlee91** [comment]
Yes it is working now.  Thank you @Jaredsohn !

**Comment by jaredsohn** [comment]
Glad that fixed it.
